accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "accounts"
urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/<username>", views.profile_view, name="profile-view"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/listing/", views.user_listing, name="user-listing"),
    path(
        "profile/listing/edit/<str:model>/<int:id>/",
        views.toggle_sold_status,
        name="toggle-sold-status",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("profile/rating/<username>", views.user_rating, name="user-rating"),
    path('notifications/', views.notifications_view, name='notifications'),
    path('contactus/', views.contactus, name='contactus'),
    path('login-history/', views.login_history, name='login-history'),
    path('change-theme/', views.change_theme, name='change-theme'),
    path("change-password/", views.change_password, name="change-password"),
    path("item-request/", views.user_item_request, name="item-request"),
    path("my-requests/", views.my_requests, name="my-requests"),
    path("delete-request/<int:requestid>", views.delete_request, name="delete-request"),
    path("my-suggestions/<int:requestid>", views.my_suggestions, name="my-suggestions")
]

books/urls.py
from django.urls import path
from . import views
 
app_name = "books"
urlpatterns = [
    path('', views.bookhome, name='home'),
    path('upload', views.upload_book, name='upload-book'),
    path('edit/<int:bookid>', views.edit_book, name='edit-book'),
    path('book-detail/<int:bookid>', views.book_detail, name='book-detail'),
]

campuscart/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)



urlpatterns = [
    path("admin/", admin.site.urls),
    path("verification/", include("verify_email.urls")),
    path("", include("accounts.urls", namespace="accounts")),
    path("product/", include("products.urls", namespace="products")),
    path('books/', include('books.urls',namespace="books")),
    path('events/', include('events.urls',namespace="events")),
    path('free/', include('freestuff.urls',namespace="freestuff")),
    path('lostandfound/', include('lostfound.urls',namespace="lostfound")),
    path('rentals/',include('rentals.urls',namespace="rentals")),
     path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),


    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = "events"
urlpatterns = [
    path('', views.eventshome, name='event-home'),
    path('event-detail/<int:event_id>', views.eventdetail, name='event-detail'),
    path('upload-event/', views.uploadevent, name='upload-event'),
    path('edit/<int:eventid>', views.editevent, name='edit-event'),
]

freestuff/urls.py
from django.urls import path
from . import views

app_name = "freestuff"
urlpatterns = [
    path('', views.index, name='home'),
    path('upload', views.upload_item, name='upload-item'),
    path('item-detail/<int:itemid>', views.item_detail, name='item-detail'),
    path('edit/<int:itemid>', views.edit_item, name='edit-item'),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.home, name="home"),
    path("sell/", views.create_product, name="sell"),
    path("detail-product/<int:pk>/", views.detail_product, name="detail_product"),
    path('edit/<int:productid>', views.edit_product, name='edit-product'),
    path(
        "interested-product/<int:pk>/",
        views.interested_product,
        name="interested_product",
    ),
]

rentals/urls.py
from django.urls import path
from . import views

app_name='rentals'
urlpatterns=[
    path('',views.rental_home,name='home'),
    path('property-detail/<int:rentid>',views.property_detail,name='property-detail'),
    path('edit-property/<int:rentid>',views.edit_property,name='edit-property'),
    path('upload-property',views.upload_property,name='upload-property')
]

accounts/views.py
import json

from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib.auth.models import auth
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate
import requests
from .models import Contact, UserComment, UserSession, UserRequest
from notifications.signals import notify
from verify_email.email_handler import send_verification_email
from .forms import (
    ContactForm,
    UserUpdateForm,
    ProfileUpdateForm,
    UserCommentsForm,
    RegistrationForm,
    LoginForm,
    ReportForm, UserRequestForm
)
from books.models import Book
from products.models import Product
from freestuff.models import FreeStuffItem
from rentals.models import Rental
from events.models import Event
from lostfound.models import LostandfoundItem

from django.utils import timezone
from datetime import timedelta
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.forms import PasswordChangeForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect("accounts:home")

    if request.method == "POST":
        form = LoginForm(None, data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                auth.login(request, user)
                return redirect("accounts:home")
        else:
            messages.add_message(
                request,
                messages.ERROR,
                "Invalid credentials! Please try again",
                extra_tags="danger",
            )
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {
        "title": "Login",
        "form": form
    })


@login_required()
def profile_view(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    comments = UserComment.objects.filter(user=user).order_by('-commented_date')

    if request.method == "POST":
        if 'reportform' in request.POST:
            report_form = ReportForm(request.POST)
            if report_form.is_valid():
                report = report_form.save(commit=False)
                report.user = user
                report.reported_by = request.user
                report.save()
                messages.success(request, "Report has been submitted")
                return redirect("accounts:profile-view", username=username)
        else:
            comment_form = UserCommentsForm(request.POST)
            if comment_form.is_valid():
                form = comment_form.save(commit=False)
                form.commented_by = request.user
                form.user = user
                form.save()
                description = f'{request.user} added a new comnent on your profile Click <a href="/profile/rating/{user.username}">here</a> to view.'
                notify.send(request.user, recipient=user, verb='Comment', description=description)
                messages.success(request, "Your comment has been added")
                return redirect("accounts:profile-view", username=username)
    else:
        report_form = ReportForm()
        comment_form = UserCommentsForm()
        myAPIKey = 'c20c43b8dddc42939c4304857ea1ce69'
        url = f"https://api.geoapify.com/v1/geocode/search?text={user.profile.address}&limit=1&apiKey={myAPIKey}"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            result = data["features"][0]
            selleruserlatitude = result["geometry"]["coordinates"][1]
            selleruserlongitude = result["geometry"]["coordinates"][0]
        else:
            selleruserlatitude = -83.06649144027972
            selleruserlongitude = 42.305201350000004

        url = f"https://api.geoapify.com/v1/geocode/search?text={request.user.profile.address}&limit=1&apiKey={myAPIKey}"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            result = data["features"][0]
            curruserlatitude = result["geometry"]["coordinates"][1]
            curruserlongitude = result["geometry"]["coordinates"][0]
        else:
            curruserlatitude = 42.31749
            curruserlongitude = -83.0387979

    return render(
        request,
        "accounts/profile_view.html",
        {
            "user": user,
            "report_form": report_form,
            'comments': comments,
            'current_user': user,
            'title': f'{user.username} Rating',
            'comment_form': comment_form,
            'selleruserlatitude': selleruserlatitude,
            'selleruserlongitude': selleruserlongitude,
            'curruserlatitude': curruserlatitude,
            'curruserlongitude': curruserlongitude
        },
    )


def register(request):
    if request.user.is_authenticated:
        return redirect("accounts:home")

    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            inactive_user = send_verification_email(request, form)
            messages.add_message(
                request,
                messages.SUCCESS,
                f"Dear {inactive_user}, "
                f"please go to you email {inactive_user.email} inbox and click on received activation "
                f"link to confirm and complete the registration. Note: Check your spam folder.",
                extra_tags="success",
            )
            return redirect("accounts:login")
    else:
        form = RegistrationForm()
    return render(request, "accounts/register.html", {
        "form": form,
        'title': 'Register'
    })


@login_required()
def home(request):
    # get all products sorted count of interested users
    products = Product.objects.filter(interested_users=request.user).order_by("-interested_users")
    current_viewed_books = request.COOKIES.get('viewed_books', '')
    current_viewed_books = [int(book) for book in current_viewed_books.split(',') if book]
    viewed_books = Book.objects.filter(id__in=current_viewed_books)
    viewed_books = sorted(viewed_books, key=lambda x: current_viewed_books.index(x.id), reverse=True)

    current_viewed_properties = request.COOKIES.get('viewed_properties', '')
    current_viewed_properties = [int(rental) for rental in current_viewed_properties.split(',') if rental]
    viewed_properties = Rental.objects.filter(id__in=current_viewed_properties)
    viewed_properties = sorted(viewed_properties, key=lambda x: current_viewed_properties.index(x.id), reverse=True)

    context = {
        "title": "Home",
        "products": products,
        'viewed_books': viewed_books,
        'viewed_properties': viewed_properties
    }
    return render(request, "accounts/home.html", context)


def user_logout(request):
    auth.logout(request)
    messages.add_message(
        request,
        messages.SUCCESS,
        "You have successfully logged out !!",
        extra_tags="success",
    )
    return redirect("accounts:login")


@login_required
def profile(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your Profile has been updated")
            return redirect("accounts:profile")
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        # get address from profile form
        try:
            address_dict = request.user.profile.address
            address_dict = json.loads(address_dict)
            coordinates = address_dict.get("coordinates")
            user_latitude = coordinates.get("latitude")
            user_longitude = coordinates.get("longitude")
            full_address = address_dict.get("full_address")
        except:
            user_latitude = 40.71669
            user_longitude = -73.961614
            full_address = ""

    return render(
        request,
        "accounts/profile.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "title": "Profile",
            "user_latitude": user_latitude,
            "full_address": full_address,
            "user_longitude": user_longitude,
        },
    )


@login_required
def notifications_view(request):
    request.user.notifications.mark_all_as_read()
    filter_by = request.GET.get("filter-by")
    print("dfg", filter_by)
    title = "Notifications"
    if filter_by == "upload":
        notifications = request.user.notifications.filter(verb="Upload")
        title = "Upload Notifications"
    elif filter_by == "comment":
        notifications = request.user.notifications.filter(verb="Comment")
        title = "Comment Notifications"
    elif filter_by == "request":
        notifications = request.user.notifications.filter(verb="Request")
        title = "Request Notifications"
    else:
        notifications = request.user.notifications.all()

    return render(
        request,
        "notifications.html",
        {"notifications": notifications, "title": title},
    )

@login_required
def user_listing(request):
    user_books = Book.objects.filter(seller=request.user)
    user_free_items = FreeStuffItem.objects.filter(seller=request.user)
    user_products = Product.objects.filter(user=request.user)
    user_rentals = Rental.objects.filter(seller=request.user)
    user_events = Event.objects.filter(organizer=request.user)

templates/accounts/contactus.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container my-4">
    <h3>Contact Us</h3>
    <form action="{% url 'accounts:contactus' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock content %}

templates/accounts/my_requests.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{{ block.super }}
{% if theme == 'primary' %}
<link rel="stylesheet" href="{% static 'css/notifications.css' %}" type="text/css" />
{% else %}
<link rel="stylesheet" href="{% static 'css/notifications-custom.css' %}" type="text/css" />
{% endif %}
{% endblock %}
{% block content %}

<div class="container position-relative">
    <div class="pt-4">
        <h1>My Requests</h1>
        <div class="notification-header-underline"></div>
    </div>
    <div class="mt-4">
        <div class="notification-container d-flex flex-column w-75 m-auto">
            {% if user_requests %}
            {% for request in user_requests %}
            <div class="notification-box d-flex align-items-center justify-content-between">
                <div class="notification-description">
                    <div>
                        <b>{{ request.item_name }} ({{ request.item_category }})</b>
                    </div>
                    <p>
                        {% autoescape off %}
                        {{ request.description }}
                        {% endautoescape %}
                    </p>
                    <div>{{ request.requested_date }}</div>
                </div>
                <div class="request-options d-flex flex-column">
                    <a class="badge badge-pill badge-danger" href="{% url 'accounts:delete-request' request.pk %}">Delete Request</a>
                    <a class="suggestions" href="{% url 'accounts:my-suggestions' request.pk %}">View Suggestions</a>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="text-center mt-4">You have not placed any requests !!</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/user_listing.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{{ block.super }}
{% if theme == 'primary' %}
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
{% else %}
<link rel="stylesheet" href="{% static 'css/books-custom.css' %}" type="text/css" />
{% endif %}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/product.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/rental.css' %}" type="text/css" />
{% endblock %}
{% block content %}
<div class="container position-relative">
  <div class="books-header pt-4">
    <h1>My Listings</h1>
    <div class="books-header-underline"></div>
  </div>
  <div class="mt-4">
    <div class="d-flex flex-wrap aui-accordion-tab2 justify-content-between" id="tabsTemplate1" role="tablist">
      <button class="aui-acc-tab-item aui-accordion-tab1 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate11" aria-expanded="true" role="tab">
        Products
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <button class="aui-acc-tab-item aui-accordion-tab2 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate12" aria-expanded="false" role="tab">
        Books
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <button class="aui-acc-tab-item aui-accordion-tab1 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate13" aria-expanded="false" role="tab">
        Free Stuff
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <button class="aui-acc-tab-item aui-accordion-tab2 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate14" aria-expanded="false" role="tab">
        Rental
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <button class="aui-acc-tab-item aui-accordion-tab1 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate15" aria-expanded="false" role="tab">
        Events
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <button class="aui-acc-tab-item aui-accordion-tab2 btn btn-text" data-toggle="collapse"
        data-target="#tabsTemplate16" aria-expanded="false" role="tab">
        Lost & Found
        <i class="aha-icon-arrow-down mx-2 d-inline-block d-md-none"></i>
      </button>
      <div id="tabsTemplate11"
        class="collapse show row w-100 no-gutters aui-accordion-content aui-accordion-content1 pt-4"
        data-parent="#tabsTemplate1" role="tabpanel">
        <div class="custom-container">
          <div class="card__container">
            {% if user_products %}
            {% for product in user_products %}
            {% if not product.is_sold %}
            <div class="property-container d-flex row">
              {% else %}
              <div class="property-container d-flex row">
                {% endif %}
                <div class="property-image">
                  <img src="{{ product.image.url }}" alt="Property Image" />
                </div>
                <div class="property-details flex-column">
                  <span class="badge badge-pill badge-info property-price">
                    ${{ product.price }}</span>
                  {% if product.is_sold %}
                  <span class="badge badge-pill badge-danger">Sold</span>
                  {% else %}
                  <a href="{% url 'products:edit-product' product.id %}" class="btn btn-sm btn-secondary">Edit</a>
                  <a class="btn btn-sm btn-outline-success"
                    href="{% url 'accounts:toggle-sold-status' 'product'  product.id %}">Mark as
                    Sold</a>
                  {% endif %}
                  <h3 class="property-title">
                    {{ product.title }}
                  </h3>
                  <div class="d-flex align-items-center">
                    Category : <b class="ml-2">{{ product.category }}</b>
                  </div>
                  <div><span>{{ rental.created_at }}</span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Items Available</h3>
              {% endif %}
            </div>
          </div>
        </div>
        <div id="tabsTemplate12" class="collapse row w-100 no-gutters aui-accordion-content aui-accordion-content2 pt-4"
          data-parent="#tabsTemplate1" role="tabpanel">
          <div class="custom-container">
            <div class="card__container">
              {% if user_books %}
              {% for book in user_books %}
              <div class="property-container d-flex row">
                <div class="property-image">
                  <img src="{{ book.book_cover.url }}" alt="Property Image" />
                </div>
                <div class="property-details flex-column">
                  <span class="badge badge-pill badge-info property-price">
                    ${{ book.price }}</span>
                  {% if book.is_sold %}
                  <span class="badge badge-pill badge-danger">Sold</span>
                  {% else %}
                  <a href="{% url 'books:edit-book' book.id %}" class="btn btn-sm btn-secondary">Edit</a>
                  <a class="btn btn-sm btn-outline-success"
                    href="{% url 'accounts:toggle-sold-status' 'book'  book.id %}">Mark as
                    Sold</a>
                  {% endif %}
                  <h3 class="property-title">
                    {{ book.title }}
                  </h3>
                  <div>Pages : <span>{{ book.pages }}</span></div>
                  <div class="d-flex align-items-center">
                    Category : <b class="ml-2">{{ book.category }}</b>
                  </div>
                  <div><span>{{ book.created_at }}</span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Items Available</h3>
              {% endif %}
            </div>
          </div>
        </div>
        <div id="tabsTemplate13" class="collapse row w-100 no-gutters aui-accordion-content aui-accordion-content1 pt-4"
          data-parent="#tabsTemplate1" role="tabpanel">
          <div class="custom-container">
            <div class="card__container">
              {% if user_free_items %}
              {% for free in user_free_items %}
              <div class="property-container d-flex row">
                <div class="property-image">
                  <img src="{{ free.item_image.url }}" alt="Property Image" />
                </div>
                <div class="property-details flex-column">
                  {% if free.is_sold %}
                  <span class="badge badge-pill badge-danger">Sold</span>
                  {% else %}
                  <a href="{% url 'freestuff:edit-item' free.id %}" class="btn btn-sm btn-secondary">Edit</a>
                  <a class="btn btn-sm btn-outline-success"
                    href="{% url 'accounts:toggle-sold-status' 'freestuff'  free.id %}">Mark as
                    Sold</a>
                  {% endif %}
                  <h3 class="property-title">{{ free.title }}</h3>
                  <div class="d-flex align-items-center">
                    Condition : <b class="ml-2">{{ free.condition }}</b>
                  </div>
                  <div class="d-flex align-items-center">
                    Category : <b class="ml-2">{{ free.category }}</b>
                  </div>
                  <div><span>{{ free.created_at }}</span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Items Available</h3>
              {% endif %}
            </div>
          </div>
        </div>
        <div id="tabsTemplate14" class="collapse row w-100 no-gutters aui-accordion-content aui-accordion-content2 pt-4"
          data-parent="#tabsTemplate1" role="tabpanel">
          <div class="custom-container">
            <div class="card__container">
              {% if user_rentals %}
              {% for rental in user_rentals %}
              <div class="property-container d-flex row">
                <div class="property-image">
                  <img src="{{ rental.property_image.url }}" alt="Property Image" />
                </div>
                <div class="property-details flex-column">
                  <span class="badge badge-pill badge-info property-price">
                    ${{ rental.price }}/month</span>
                  {% if rental.is_sold %}
                  <span class="badge badge-pill badge-danger">Sold</span>
                  {% else %}
                  <a href="{% url 'rentals:edit-property' rental.id %}" class="btn btn-sm btn-secondary">Edit</a>
                  <a class="btn btn-sm btn-outline-success"
                    href="{% url 'accounts:toggle-sold-status' 'rental'  rental.id %}">Mark as
                    Sold</a>
                  {% endif %}
                  <h3 class="property-title">{{ rental.property_name }}
                  </h3>
                  <div class="d-flex align-items-center">
                    <span class="material-symbols-outlined mr-1">
                      pin_drop
                    </span>
                    {{ rental.address }}
                  </div>
                  <div><span>{{ rental.created_at }}</span> | <span>{{ rental.city }}</span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Items Available</h3>
              {% endif %}
            </div>
          </div>
        </div>
        <div id="tabsTemplate15" class="collapse row w-100 no-gutters aui-accordion-content aui-accordion-content1 pt-4"
          data-parent="#tabsTemplate1" role="tabpanel">
          <div class="custom-container">
            <div class="card__container">
              {% if user_events %}
              {% for event in user_events %}
              <div class="property-container d-flex row">
                <div class="property-image">
                  <img src="{{ event.image.url }}" alt="Property Image" />
                </div>
                <div class="property-details flex-column">
                  <span class="badge badge-pill badge-info property-price">
                    ${{ event.price }}</span>
                  {% if event.is_sold %}
                  <span class="badge badge-pill badge-danger">Sold</span>
                  {% else %}
                  <a class="btn btn-sm btn-secondary" href="{% url 'events:edit-event' event.id %}">Edit</a>
                  <a class="btn btn-sm btn-outline-success"
                    href="{% url 'accounts:toggle-sold-status' 'events'  event.id %}">Mark as
                    Sold</a>
                  {% endif %}
                  <h3 class="property-title">{{ event.title }}</h3>
                  <div class="d-flex align-items-center">
                    Location : <b class="ml-2">{{ event.location }}</b>
                  </div>
                  <div class="d-flex align-items-center">
                    Category : <b class="ml-2">{{ event.category }}</b>
                  </div>
                  <div class="d-flex align-items-center">
                    Total Seats : <b class="ml-2">{{ event.total_seats }}</b>
                  </div>
                  <div><span>{{ event.date_and_time }}</span></span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Items Available</h3>
              {% endif %}
            </div>
          </div>
        </div>
        <div id="tabsTemplate16" class="collapse row w-100 no-gutters aui-accordion-content aui-accordion-content2 pt-4"
          data-parent="#tabsTemplate1" role="tabpanel">
          <div class="custom-container">
            <div class="card__container">
              {% if user_lostfound %}
              {% for post in user_lostfound %}
              <div class="property-container d-flex row">
                <div class="property-image">
                  <img src="{{ post.image.url }}" alt="LostFound Image" />
                </div>
                <div class="property-details flex-column">
                  <a class="btn btn-sm btn-secondary" href="{% url 'lostfound:edit-post' post.id %}">Edit</a>
                  <h3 class="property-title">{{ post.title }}</h3>
                  <div class="d-flex align-items-center">
                    Location : <b class="ml-2">{{ post.location }}</b>
                  </div>
                  <div class="d-flex align-items-center">
                    Category : <b class="ml-2">{{ post.category }}</b>
                  </div>
                  <div><span>{{ post.post_date }}</span></span></div>
                </div>
              </div>
              {% endfor %}
              {% else %}
              <h3>No Posts Available</h3>
              {% endif %}            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}