accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "accounts"
urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/<username>", views.profile_view, name="profile-view"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/listing/", views.user_listing, name="user-listing"),
    path(
        "profile/listing/edit/<str:model>/<int:id>/",
        views.toggle_sold_status,
        name="toggle-sold-status",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("profile/rating/<username>", views.user_rating, name="user-rating"),
    path('notifications/', views.notifications_view, name='notifications'),
    path('contactus/', views.contactus, name='contactus'),
    path('login-history/', views.login_history, name='login-history'),
    path('change-theme/', views.change_theme, name='change-theme'),
    path("change-password/", views.change_password, name="change-password"),
    path("item-request/", views.user_item_request, name="item-request"),
    path("my-requests/", views.my_requests, name="my-requests"),
    path("delete-request/<int:requestid>", views.delete_request, name="delete-request"),
    path("my-suggestions/<int:requestid>", views.my_suggestions, name="my-suggestions")
]

books/urls.py
from django.urls import path
from . import views
 
app_name = "books"
urlpatterns = [
    path('', views.bookhome, name='home'),
    path('upload', views.upload_book, name='upload-book'),
    path('edit/<int:bookid>', views.edit_book, name='edit-book'),
    path('book-detail/<int:bookid>', views.book_detail, name='book-detail'),
]

campuscart/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)



urlpatterns = [
    path("admin/", admin.site.urls),
    path("verification/", include("verify_email.urls")),
    path("", include("accounts.urls", namespace="accounts")),
    path("product/", include("products.urls", namespace="products")),
    path('books/', include('books.urls',namespace="books")),
    path('events/', include('events.urls',namespace="events")),
    path('free/', include('freestuff.urls',namespace="freestuff")),
    path('lostandfound/', include('lostfound.urls',namespace="lostfound")),
    path('rentals/',include('rentals.urls',namespace="rentals")),
     path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),


    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Book(models.Model):
    BOOKS_CATEGORY = [
        ("Fiction", "Fiction"),
        ("Non-Fiction", "Non-Fiction"),
        ("Academic", "Academic"),
        ("Children", "Children"),
        ("Art & Photography", "Art & Photography"),
        ("Cookbooks", "Cookbooks"),
        ("Travel", "Travel"),
        ("Health & Wellness", "Health & Wellness"),
        ("Religion & Spirituality", "Religion & Spirituality"),
        ("Hobbies & Crafts", "Hobbies & Crafts"),
        ("Sports & Recreation", "Sports & Recreation"),
        ("Science Fiction & Fantasy", "Science Fiction & Fantasy"),
        ("Horror", "Horror"),
        ("Poetry", "Poetry"),
        ("Drama", "Drama"),
        ("Others", "Others"),
    ]

    CONDITION_LIST = [
        ("New", "New"),
        ("Used", "Used"),
    ]
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    pages = models.PositiveIntegerField()
    language = models.CharField(max_length=50, default="English")
    category = models.CharField(
        max_length=50, choices=BOOKS_CATEGORY, default="Others", blank=True
    )
    book_cover = models.ImageField(
        upload_to="upload_book/", default="upload_book/book-cover.png", blank=True
    )
    is_sold = models.BooleanField(default=False)
    condition = models.CharField(max_length=255, choices=CONDITION_LIST, default="New")

    def __str__(self):
        return self.title

    def count_views(self):
        return BookViews.objects.filter(book=self).count()


class BookViews(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user_session_key = models.CharField(max_length=60)
    viewed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.book.title}"

books/forms.py
# forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'price', 'pages', 'language', 'category','condition', 'book_cover']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('title', css_class='form-control'),
            Field('author', css_class='form-control'),
            Field('description', css_class='form-control'),
            Field('price', css_class='form-control'),
            Field('pages', css_class='form-control'),
            Field('language', css_class='form-control'),
            Field('category', css_class='form-control'),
            Field('book_cover', css_class='form-control'),
        )


class BooksFilter(forms.Form):
    BOOKS_CATEGORY = [
        ("", "----"),
        ("Fiction", "Fiction"),
        ("Non-Fiction", "Non-Fiction"),
        ("Academic", "Academic"),
        ("Children", "Children"),
        ("Art & Photography", "Art & Photography"),
        ("Cookbooks", "Cookbooks"),
        ("Travel", "Travel"),
        ("Health & Wellness", "Health & Wellness"),
        ("Religion & Spirituality", "Religion & Spirituality"),
        ("Hobbies & Crafts", "Hobbies & Crafts"),
        ("Sports & Recreation", "Sports & Recreation"),
        ("Science Fiction & Fantasy", "Science Fiction & Fantasy"),
        ("Horror", "Horror"),
        ("Poetry", "Poetry"),
        ("Drama", "Drama"),
        ("Others", "Others"),
    ]
    PRICE_RANGE = [
        ("", "----"),
        ("0-10", "$0-10"),
        ("10-20", "$10-20"),
        ("20-30", "$20-30"),
        ("30-40", "$30-40"),
        ("40-50", "$40-50"),
        ("50-1000", "$50 or More"),
    ]
    name = forms.CharField(label="Book Name",required=False)
    category = forms.ChoiceField(
        choices=BOOKS_CATEGORY, required=False, label="Category"
    )
    price = forms.ChoiceField(choices=PRICE_RANGE, required=False, label="Price Range")

books/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from notifications.signals import notify
from django.contrib import messages
from django.core.paginator import Paginator
from .forms import BookForm,BooksFilter
from .models import Book, BookViews


@login_required
# Create your views here.
def bookhome(request):
    if request.method == 'GET':
        form = BooksFilter(request.GET)
        if form.is_valid():
            book_name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            price_range = form.cleaned_data['price']
            books = Book.objects.all()
            if category:
                books = books.filter(category=category)
            if price_range:
                price = price_range.split('-')
                books = books.filter(price__gte=price[0], price__lte=price[1])
            if book_name:
                books = books.filter(title__contains=book_name)

            paginator = Paginator(books, 9)

            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)
    else:
        books = Book.objects.all()
    return render(request, 'books/home.html', {
        'title': 'Books',
        'all_books': books,
        'form': form,
        'page_obj':page_obj
    })


@login_required
def upload_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.seller = request.user
            book.save()
            sender = get_user_model().objects.get(username=request.user)
            receiver = get_user_model().objects.exclude(username=request.user)
            description = f'<b>{book.title}</b> (Book). Click <a href="/books/book-detail/{book.id}">here</a> to view.'
            notify.send(sender, recipient=receiver, verb='Upload', description=description)
            return redirect('books:home')
    else:
        form = BookForm()
    return render(request, 'books/upload_book.html', {
        'form': form,
        'title': 'Upload Book'
    })


@login_required
def book_detail(request, bookid):
    current_book = get_object_or_404(Book, pk=bookid)

    # get same category books
    same_category_books = Book.objects.exclude(pk=current_book.id).filter(category=current_book.category)

    # Update viewed_books in the cookies
    current_viewed_books = request.COOKIES.get('viewed_books', '')
    current_viewed_books = [int(book) for book in current_viewed_books.split(',') if book]
    if bookid not in current_viewed_books:
        current_viewed_books.append(bookid)

    current_viewed_books_str = ','.join(map(str, current_viewed_books))
    book_view = BookViews.objects.filter(user_session_key=request.session.session_key,book=current_book)
    if not book_view.exists():
        BookViews.objects.create(book=current_book, user=request.user, user_session_key=request.session.session_key)

    response = render(request, 'books/book_detail.html', {
        'title': current_book.title,
        'book': current_book,
        'same_category_books': same_category_books
    })
    response.set_cookie('viewed_books', current_viewed_books_str, max_age=36000)
    return response


@login_required
def edit_book(request, bookid):
    my_book = get_object_or_404(Book, pk=bookid)
    if my_book.seller != request.user:
        messages.success(request, "You don't have the access to the book", extra_tags='danger')
        return redirect('accounts:user-listing')
    if request.method == 'POST':
        if 'action' in request.POST:
            form = BookForm(request.POST, request.FILES, instance=my_book)
            if form.is_valid():
                book = form.save(commit=False)
                book.save()
                return redirect('accounts:user-listing')
        else:
            my_book.delete()
            messages.success(request, "Your Book has been deleted", extra_tags='danger')
            return redirect('accounts:user-listing')
    else:
        form = BookForm(instance=my_book)
    return render(request, 'books/edit_book.html', {
        'form': form,
        'title': 'Edit Book'
    })

templates/books/book_detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/common.css' %}" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>{{ book.title }}</h1>
        <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <section class="book-detail-section d-flex justify-content-between flex-column flex-lg-row">
            <div class="book-image d-flex justify-content-center align-items-center one-half">
                <img class="mw-100 h-auto" src="{{ book.book_cover.url }}" alt="{{ book.title }}">
            </div>
            <div class="book-information one-half position-relative">
                <h4>By {{ book.author }} (Author)</h4>
                <span>${{ book.price }}</span>
                <div>
                    {% if book.is_sold %}
                    <span class="badge badge-pill badge-danger">Sold</span>
                    {% endif %}
                </div>
                <p class="book-description">{{ book.description }}</p>
                <div class="position-absolute seller-information w-100">
                    <p>Seller Information</p>
                    <div class="d-flex align-items-center justify-content-between">
                        <a class="contact-seller"
                            href="MSTeams:/l/chat/0/0?users={{ book.seller.email }}&message=Is it available">Contact
                            Seller</a>
                        <div>
                            <a href="{% url 'accounts:profile-view' book.seller.username %}" class="profile-link-url">
                                <b>{{ book.seller.first_name }} {{ book.seller.last_name }}</b></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="book-additional-details my-4 d-flex flex-column">
            <div class="book-extra-info">
                <span>Language : </span>
                <span>{{ book.language }}</span>
            </div>
            <div class="book-extra-info">
                <span>Length : </span>
                <span>{{ book.pages }} pages</span>
            </div>
            <div class="book-extra-info">
                <span>Category : </span>
                <span>{{ book.category }}</span>
            </div>
            <div class="book-extra-info">
                <span>Condition : </span>
                <span>{{ book.condition }}</span>
            </div>
        </section>
        {% if same_category_books %}
        <h2 class="mt-4">Books with Similar Category</h2>
        <div id="multiple-carousel-slider" class="carousel slide aui-multiple-carousel" data-ride="carousel"
            data-interval="false">
            <div id="carousel-container" class="carousel-inner row p-0 m-0">
                {% for book in same_category_books %}
                <div
                    class="carousel-item carousel-column col-12 col-sm-6 col-md-4 col-lg-3 mt-lg-4 ci {% if forloop.first %}active{% endif %}">
                    <a href="{% url 'books:book-detail' book.id %}" class="book-card book-card-shadow-none">
                        <div class="book-card__cover">
                            <div class="book-card__book">
                                <div class="book-card__book-front">
                                    <img class="book-card__img" src="{{ book.book_cover.url }}" alt="Book Cover" />
                                </div>
                                <div class="book-card__book-back"></div>
                                <div class="book-card__book-side"></div>
                            </div>
                        </div>
                        <div>
                            <div class="book-card__title">
                                {{ book.title }}
                            </div>
                            <div class="book-card__author">
                                <b>{{ book.category }}</b>
                            </div>
                            <div class="book-card__author">
                                By {{ book.author }}
                            </div>
                            <div class="book-card__author">
                                ${{ book.price }}
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <a class="carousel-control-next" href="#multiple-carousel-slider" role="button" data-slide="next">
                <span class="carousel-control-next-icon aha-icon-arrow-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            <a class="carousel-control-prev action-disable" href="#multiple-carousel-slider" role="button"
                data-slide="prev">
                <span class="carousel-control-prev-icon aha-icon-arrow-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/books/edit_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>Edit your Book</h1>
            <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
                {% for field in form %}
                <div class="col-sm-6">
                    {{ field|as_crispy_field }}
                </div>
                {% endfor %}
            </div>
            <div class="d-flex">
                <button style="border-radius:2rem;" class=" mr-4 btn btn-success d-block mt-4" type="submit"
                    name="action">Edit</button>
                <a style="border-radius:2rem;" class="btn btn-danger d-block mt-4 text-light" data-toggle="modal"
                    data-target="#deletemodelbook">Delete</a>
                <div class="modal fade show aui-modal" id="deletemodelbook" tabindex="-1" aria-labelledby="modalLabel"
                    aria-modal="true" role="dialog">
                    <div class="modal-dialog modal-dialog-centered modal-sm">
                        <div class="modal-content">
                            <div class="modal-body p-0">
                                <div class="text-center">
                                    <p>Are you sure you want to delete this Book?</p>
                                    <div class="mt-4">
                                        <button class="btn btn-primary btn-round btn-sm mx-2" type="submit"
                                            name="delete" data-toggle="modal"
                                            data-target="#deletemodelbook">Yes</button>
                                        <button class="btn btn-secondary btn-round btn-sm mx-2" data-dismiss="modal"
                                            aria-label="Close">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/books/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
{% if theme == 'primary' %}
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
{% else %}
<link rel="stylesheet" href="{% static 'css/books-custom.css' %}" type="text/css" />
{% endif %}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
{% endblock %}
{% block content %}

<div class="container position-relative">
    <a class="position-absolute upload-btn" href='{% url "books:upload-book" %}'>Upload your Book</a>
    <div class="pt-4">
        <h1>Books</h1>
        <div class="header-underline"></div>
    </div>
    <div class="mt-4 mb-3">
        <div>
            <form class="d-flex">
                <div class="input-group align-items-end justify-content-start">
                    {{ form|crispy }}
                    <button class="btn" type="submit">Search</button>
                    <a href="{% url 'books:home' %}" class="text-link float-end">Reset</a>
                </div>
            </form>
        </div>
    </div>
    <div class="mt-4">
        <div class="custom-container">
            <div class="card__container">
                {% for book in page_obj %}
                <a href="{% url 'books:book-detail' book.id %}" class="book-card">
                    <div class="book-card__cover">
                        <div class="book-card__book">
                            <div class="book-card__book-front">
                                <img class="book-card__img" src="{{ book.book_cover.url }}" alt="Book Cover" />
                            </div>
                            <div class="book-card__book-back"></div>
                            <div class="book-card__book-side"></div>
                        </div>
                    </div>
                    <div class="position-relative">
                        <div class="book-card__title my-2">
                            {{ book.title }}
                        </div>
                        <div class="book-card__author">
                            <b>{{ book.category }}</b>
                        </div>
                        <div class="book-card__author">
                            By {{ book.author }}
                        </div>
                        <div class="book-card__author">
                            ${{ book.price }}
                        </div>
                        <div class="book-card__author">
                            {{ book.condition }}
                        </div>
                        {% if book.is_sold %}
                        <div class="position-absolute right-0 bottom-0">
                            <span class="badge badge-pill badge-danger">Sold</span>
                        </div>
                        {% else %}
                        <div class="book-card__author d-flex align-items-center justify-content-end">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                            <span class="ml-2">{{ book.count_views }}</span>
                        </div>
                        {% endif %}
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="d-flex align-items-center justify-content-center mt-5">
                <div class="pagination align-items-center justify-content-center">
                    {% if page_obj.has_previous %}
                    <span class="page-item">
                        <a href="?page=1" class="page-link p-2">&laquo; First</a>
                    </span>
                    <span class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link p-2">Previous</a>
                    </span>
                    {% endif %}
                    <span class="aui-tag-list">
                        <span class="aui-tag-item mx-2">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                    </span>
                    {% if page_obj.has_next %}
                    <span class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link p-2">Next</a>
                    </span>
                    <span class="page-item">
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link p-2">Last &raquo;</a>
                    </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/books/upload_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>Upload your Book</h1>
            <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
                {% for field in form %}
                <div class="col-sm-6">
                    {{ field|as_crispy_field }}
                </div>
                {% endfor %}
            </div>
            <button style="border-radius:2rem;" class="btn btn-success d-block mt-4" type="submit" name="action">Add
                your Book</button>
        </form>
    </div>
</div>
{% endblock content %}