accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "accounts"
urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/<username>", views.profile_view, name="profile-view"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/listing/", views.user_listing, name="user-listing"),
    path(
        "profile/listing/edit/<str:model>/<int:id>/",
        views.toggle_sold_status,
        name="toggle-sold-status",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("profile/rating/<username>", views.user_rating, name="user-rating"),
    path('notifications/', views.notifications_view, name='notifications'),
    path('contactus/', views.contactus, name='contactus'),
    path('login-history/', views.login_history, name='login-history'),
    path('change-theme/', views.change_theme, name='change-theme'),
    path("change-password/", views.change_password, name="change-password"),
    path("item-request/", views.user_item_request, name="item-request"),
    path("my-requests/", views.my_requests, name="my-requests"),
    path("delete-request/<int:requestid>", views.delete_request, name="delete-request"),
    path("my-suggestions/<int:requestid>", views.my_suggestions, name="my-suggestions")
]

books/urls.py
from django.urls import path
from . import views
 
app_name = "books"
urlpatterns = [
    path('', views.bookhome, name='home'),
    path('upload', views.upload_book, name='upload-book'),
    path('edit/<int:bookid>', views.edit_book, name='edit-book'),
    path('book-detail/<int:bookid>', views.book_detail, name='book-detail'),
]

campuscart/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)



urlpatterns = [
    path("admin/", admin.site.urls),
    path("verification/", include("verify_email.urls")),
    path("", include("accounts.urls", namespace="accounts")),
    path("product/", include("products.urls", namespace="products")),
    path('books/', include('books.urls',namespace="books")),
    path('events/', include('events.urls',namespace="events")),
    path('free/', include('freestuff.urls',namespace="freestuff")),
    path('lostandfound/', include('lostfound.urls',namespace="lostfound")),
    path('rentals/',include('rentals.urls',namespace="rentals")),
     path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),


    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freestuff/urls.py
from django.urls import path
from . import views

app_name = "freestuff"
urlpatterns = [
    path('', views.index, name='home'),
    path('upload', views.upload_item, name='upload-item'),
    path('item-detail/<int:itemid>', views.item_detail, name='item-detail'),
    path('edit/<int:itemid>', views.edit_item, name='edit-item'),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.home, name="home"),
    path("sell/", views.create_product, name="sell"),
    path("detail-product/<int:pk>/", views.detail_product, name="detail_product"),
    path('edit/<int:productid>', views.edit_product, name='edit-product'),
    path(
        "interested-product/<int:pk>/",
        views.interested_product,
        name="interested_product",
    ),
]

freestuff/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class FreeStuffItem(models.Model):
    CATEGORY_LIST = [
        ("Electronics", "Electronics"),
        ("Clothing", "Clothing"),
        ("Shoes", "Shoes"),
        ("Furniture", "Furniture"),
        ("Book", "Book"),
        ("Others", "Others"),
    ]
    CONDITION_LIST = [
        ("New", "New"),
        ("Used", "Used"),
    ]
    title = models.CharField(max_length=255)
    description = models.TextField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    item_image = models.ImageField(
        upload_to="freestuff/", default="freestuff/default.png"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(
        max_length=255, choices=CATEGORY_LIST, blank=True, null=True, default="Others"
    )
    condition = models.CharField(max_length=255, choices=CONDITION_LIST, default="New")
    is_sold = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def count_views(self):
        return FreeItemViews.objects.filter(free=self).count()


class FreeItemViews(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    free = models.ForeignKey(FreeStuffItem, on_delete=models.CASCADE)
    user_session_key = models.CharField(max_length=60)
    viewed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.free.title}"

freestuff/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
from .models import FreeStuffItem


class FreeItemForm(forms.ModelForm):
    class Meta:
        model = FreeStuffItem
        fields = ['title', 'description', 'quantity','category','condition', 'item_image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('title', css_class='form-control'),
            Field('description', css_class='form-control'),
            Field('quantity', css_class='form-control'),
            Field('category', css_class='form-control'),
            Field('condition', css_class='form-control'),
            Field('item_image', css_class='form-control'),
        )

class FreeItemFiltersForm(forms.Form):
    CATEGORY_LIST = [
        ("", "----"),
        ("Electronics", "Electronics"),
        ("Clothing", "Clothing"),
        ("Shoes", "Shoes"),
        ("Furniture", "Furniture"),
        ("Others", "Others"),
    ]
    CONDITION_LIST = [
        ("", "----"),
        ("New", "New"),
        ("Used", "Used"),
    ]
    condition = forms.ChoiceField(
        choices=CONDITION_LIST, required=False, label="Condition"
    )
    category = forms.ChoiceField(
        choices=CATEGORY_LIST, required=False, label="Category"
    )

freestuff/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from notifications.signals import notify
from products.models import Product
from .forms import FreeItemForm, FreeItemFiltersForm
from .models import FreeStuffItem, FreeItemViews
from django.contrib import messages


@login_required
def index(request):
    if request.method == 'GET':
        form = FreeItemFiltersForm(request.GET)
        items = FreeStuffItem.objects.all()
        if form.is_valid():
            category = form.cleaned_data.get('category')
            condition = form.cleaned_data.get('condition')
            if category and condition:
                items = items.filter(category=category, condition=condition)
            elif category:
                items = items.filter(category=category)
            elif condition:
                items = items.filter(condition=condition)

            paginator = Paginator(items, 9)

            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)
    else:
        items = FreeStuffItem.objects.all()
    return render(request, 'freestuff/home.html', {
        'items': items,
        'title': 'Free Stuff',
        'form': form,
        'page_obj': page_obj
    })


@login_required
def upload_item(request):
    if request.method == 'POST':
        form = FreeItemForm(request.POST, request.FILES)
        if form.is_valid():
            free_item = form.save(commit=False)
            free_item.seller = request.user
            free_item.save()
            sender = get_user_model().objects.get(username=request.user)
            receiver = get_user_model().objects.exclude(username=request.user)
            description = f'<b>{free_item.title}</b> (Free {free_item.category} Item). Click <a href="/free/item-detail/{free_item.id}">here</a> to view.'
            notify.send(sender, recipient=receiver, verb='Upload', description=description)
            return redirect('freestuff:home')
    else:
        form = FreeItemForm()
    return render(request, 'freestuff/upload_item.html', {
        'form': form,
        'title': 'Upload your Item'
    })


@login_required
def item_detail(request, itemid):
    current_item = get_object_or_404(FreeStuffItem, pk=itemid)
    same_category_free_items = FreeStuffItem.objects.exclude(pk=current_item.pk).filter(category=current_item.category)
    same_category_products = Product.objects.filter(category=current_item.category)
    free_view = FreeItemViews.objects.filter(user_session_key=request.session.session_key, free=current_item)
    if not free_view.exists():
        FreeItemViews.objects.create(free=current_item, user=request.user, user_session_key=request.session.session_key)
    return render(request, 'freestuff/item_detail.html', {
        'title': current_item.title,
        'item': current_item,
        'same_category_free_items': same_category_free_items,
        'same_category_products': same_category_products
    })


@login_required
def edit_item(request, itemid):
    my_item = get_object_or_404(FreeStuffItem, pk=itemid)
    if my_item.seller != request.user:
        messages.success(request, "You don't have the access to the Item", extra_tags='danger')
        return redirect('accounts:user-listing')
    if request.method == 'POST':
        if 'action' in request.POST:
            form = FreeItemForm(request.POST, request.FILES, instance=my_item)
            if form.is_valid():
                book = form.save(commit=False)
                book.save()
                return redirect('accounts:user-listing')
        else:
            my_item.delete()
            messages.success(request, "Your Item has been deleted", extra_tags='danger')
            return redirect('accounts:user-listing')
    else:
        form = FreeItemForm(instance=my_item)
    return render(request, 'freestuff/edit_item.html', {
        'form': form,
        'title': 'Edit Item'
    })

templates/freestuff/edit_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>Edit your Item</h1>
            <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
                {% for field in form %}
                <div class="col-sm-6">
                    {{ field|as_crispy_field }}
                </div>
                {% endfor %}
            </div>
            <div class="d-flex">
                <button style="border-radius:2rem;" class=" mr-4 btn btn-success d-block mt-4" type="submit"
                    name="action">Edit</button>
                <a style="border-radius:2rem;" class="btn btn-danger d-block mt-4 text-light" data-toggle="modal"
                    data-target="#deletemodelbook">Delete</a>
                <div class="modal fade show aui-modal" id="deletemodelbook" tabindex="-1" aria-labelledby="modalLabel"
                    aria-modal="true" role="dialog">
                    <div class="modal-dialog modal-dialog-centered modal-sm">
                        <div class="modal-content">
                            <div class="modal-body p-0">
                                <div class="text-center">
                                    <p>Are you sure you want to delete this Book?</p>
                                    <div class="mt-4">
                                        <button class="btn btn-primary btn-round btn-sm mx-2" type="submit"
                                            name="delete" data-toggle="modal"
                                            data-target="#deletemodelbook">Yes</button>
                                        <button class="btn btn-secondary btn-round btn-sm mx-2" data-dismiss="modal"
                                            aria-label="Close">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/freestuff/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
{% endblock %}
{% block content %}
<div class="container position-relative">
    <a class="position-absolute upload-btn" href='{% url "freestuff:upload-item" %}'>Upload your free Item</a>
    <div class="pt-4">
        <h1>Free Items</h1>
        <div class="header-underline"></div>
    </div>
    <div class="mt-4 mb-3">
        <div>
            <form class="d-flex">
                <div class="input-group align-items-end justify-content-end">
                    {{ form|crispy }}
                    <button class="btn" type="submit">Search</button>
                    <a href="{% url 'freestuff:home' %}" class="text-link float-end">Reset</a>
                </div>
            </form>
        </div>
    </div>
    <div class="mt-4">
        <div class="custom-container">
            <div class="card__container">
                {% for item in page_obj %}
                <article class="card__article">
                    <img src="{{ item.item_image.url }}" alt="image" class="card__img">

                    <div class="card__data">
                        {% if item.is_sold %}
                        <div>
                            <span class="badge badge-pill badge-danger">Sold</span>
                        </div>
                        {% else %}
                        <div class="book-card__author d-flex align-items-center justify-content-end">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                            <span class="ml-2">{{ item.count_views }}</span>
                        </div>
                        {% endif %}
                        <span class="card__description">{{ item.condition }}</span>
                        <h2 class="card__title">{{ item.title }}</h2>
                        <span class="card__description">{{ item.category }}</span>
                        <a href="{% url 'freestuff:item-detail' item.id %}" class="card__button">Read More</a>
                    </div>
                </article>
                {% endfor %}
            </div>
            <div class="d-flex align-items-center justify-content-center mt-5">
                <div class="pagination align-items-center justify-content-center">
                    {% if page_obj.has_previous %}
                    <span class="page-item">
                        <a href="?page=1" class="page-link p-2">&laquo; First</a>
                    </span>
                    <span class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link p-2">Previous</a>
                    </span>
                    {% endif %}
                    <span class="aui-tag-list">
                        <span class="aui-tag-item mx-2">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                    </span>
                    {% if page_obj.has_next %}
                    <span class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link p-2">Next</a>
                    </span>
                    <span class="page-item">
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link p-2">Last &raquo;</a>
                    </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/freestuff/item_detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/books.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/common.css' %}" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>{{ item.title }}</h1>
        <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <section class="book-detail-section d-flex justify-content-between flex-column flex-lg-row-reverse mb-4">
            <div class="book-image d-flex justify-content-center align-items-center one-half">
                <img class="mw-100 h-auto" src="{{ item.item_image.url }}" alt="{{ item.title }}">
            </div>
            <div class="item-information one-half position-relative">
                <div>
                    {% if item.is_sold %}
                    <span class="badge badge-pill badge-danger">Sold</span>
                    {% endif %}
                </div>
                <h6>Quantity : {{ item.quantity }}</h6>
                <ul class="aui-tag-list">
                    <li class="aui-tag-item font-italic">{{ item.condition }}</li>
                    <li class="aui-tag-item font-italic">{{ item.category }}</li>
                </ul>
                <p class="item-description mt-2">{{ item.description }}</p>
                <div class="position-absolute seller-information w-100">
                    <p>Seller Information</p>
                    <div class="d-flex align-items-center justify-content-between">
                        <a class="contact-seller"
                            href="MSTeams:/l/chat/0/0?users={{ book.seller.email }}&message=Is it available">Contact
                            Seller</a>
                        <div>
                            <a href="{% url 'accounts:profile-view' item.seller.username %}" class="profile-link-url">
                                <b>{{ item.seller.get_full_name }}</b></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% if same_category_products or same_category_free_items %}
        <h2 class="mt-4">Products with Similar Category</h2>
        <div id="multiple-carousel-slider" class="carousel slide aui-multiple-carousel" data-ride="carousel"
            data-interval="false">
            <div id="carousel-container" class="carousel-inner row p-0 m-0 card__container">
                {% for item in same_category_free_items %}
                <article class="card__article carousel-item carousel-column ci {% if forloop.first %}active{% endif %}">
                    <img src="{{ item.item_image.url }}" alt="image" class="card__img">
                    <div class="card__data">
                        {% if item.is_sold %}
                        <div>
                            <span class="badge badge-pill badge-danger">Sold</span>
                        </div>
                        {% else %}
                        <div class="book-card__author d-flex align-items-center justify-content-end">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                            <span class="ml-2">{{ item.count_views }}</span>
                        </div>
                        {% endif %}
                        <span class="card__description">{{ item.condition }}</span>
                        <h2 class="card__title">{{ item.title }}</h2>
                        <span class="card__description">{{ item.category }}</span>
                        <a href="{% url 'freestuff:item-detail' item.id %}" class="card__button">Read More</a>
                    </div>
                </article>
                {% endfor %}
                {% for item in same_category_products %}
                <article class="card__article carousel-item carousel-column ci {% if forloop.first %}active{% endif %}">
                    <img src="{{ item.image.url }}" alt="image" class="card__img">
                    <div class="card__data">
                        {% if item.is_sold %}
                        <div>
                            <span class="badge badge-pill badge-danger">Sold</span>
                        </div>
                        {% else %}
                        <div class="book-card__author d-flex align-items-center justify-content-end">
                            <span class="material-symbols-outlined">
                                visibility
                            </span>
                            <span class="ml-2">{{ item.count_views }}</span>
                        </div>
                        {% endif %}
                        <p>${{ item.price }}</p>
                        <span class="card__description">{{ item.condition }}</span>
                        <h2 class="card__title">{{ item.title }}</h2>
                        <span class="card__description">{{ item.category }}</span>
                        <a href="{% url 'products:detail_product' item.pk %}" class="card__button">Read More</a>
                    </div>
                </article>
                {% endfor %}
            </div>
            <a class="carousel-control-next" href="#multiple-carousel-slider" role="button" data-slide="next">
                <span class="carousel-control-next-icon aha-icon-arrow-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            <a class="carousel-control-prev action-disable" href="#multiple-carousel-slider" role="button"
                data-slide="prev">
                <span class="carousel-control-prev-icon aha-icon-arrow-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/freestuff/upload_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/free.css' %}" type="text/css" />
{% endblock %}
{% block content %}

<div class="container">
    <div class="pt-4">
        <h1>Upload your Free Item</h1>
            <div class="header-underline"></div>
    </div>
    <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
                {% for field in form %}
                <div class="col-sm-6">
                    {{ field|as_crispy_field }}
                </div>
                {% endfor %}
            </div>
            <button style="border-radius:2rem;" class="btn btn-success d-block mt-4" type="submit" name="action">Add
                your Item</button>
        </form>
    </div>
</div>
{% endblock content %}