accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "accounts"
urlpatterns = [
    path('', views.home, name='home'),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("profile/<username>", views.profile_view, name="profile-view"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/listing/", views.user_listing, name="user-listing"),
    path(
        "profile/listing/edit/<str:model>/<int:id>/",
        views.toggle_sold_status,
        name="toggle-sold-status",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("profile/rating/<username>", views.user_rating, name="user-rating"),
    path('notifications/', views.notifications_view, name='notifications'),
    path('contactus/', views.contactus, name='contactus'),
    path('login-history/', views.login_history, name='login-history'),
    path('change-theme/', views.change_theme, name='change-theme'),
    path("change-password/", views.change_password, name="change-password"),
    path("item-request/", views.user_item_request, name="item-request"),
    path("my-requests/", views.my_requests, name="my-requests"),
    path("delete-request/<int:requestid>", views.delete_request, name="delete-request"),
    path("my-suggestions/<int:requestid>", views.my_suggestions, name="my-suggestions")
]

books/urls.py
from django.urls import path
from . import views
 
app_name = "books"
urlpatterns = [
    path('', views.bookhome, name='home'),
    path('upload', views.upload_book, name='upload-book'),
    path('edit/<int:bookid>', views.edit_book, name='edit-book'),
    path('book-detail/<int:bookid>', views.book_detail, name='book-detail'),
]

campuscart/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)



urlpatterns = [
    path("admin/", admin.site.urls),
    path("verification/", include("verify_email.urls")),
    path("", include("accounts.urls", namespace="accounts")),
    path("product/", include("products.urls", namespace="products")),
    path('books/', include('books.urls',namespace="books")),
    path('events/', include('events.urls',namespace="events")),
    path('free/', include('freestuff.urls',namespace="freestuff")),
    path('lostandfound/', include('lostfound.urls',namespace="lostfound")),
    path('rentals/',include('rentals.urls',namespace="rentals")),
     path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),


    path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = "events"
urlpatterns = [
    path('', views.eventshome, name='event-home'),
    path('event-detail/<int:event_id>', views.eventdetail, name='event-detail'),
    path('upload-event/', views.uploadevent, name='upload-event'),
    path('edit/<int:eventid>', views.editevent, name='edit-event'),
]

templates/base.html
{% load static %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Campus Cart | {{ title }}</title>
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
  <link rel="stylesheet" href="https://aui.heart.org/aha-ui/dev/1.0.3/dist/css/aha-dist.css" />
  <script src="https://aui.heart.org/aha-ui/dev/1.0.3/dist/js/aha-dist.js"></script>
  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@1,300..900&display=swap" rel="stylesheet">
  {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  {% if theme == 'primary' %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" />
  {% else %}
  <link rel="stylesheet" href="{% static 'css/base-custom.css' %}" type="text/css" />
  {% endif %}
  <link rel="stylesheet" href="{% static 'css/common.css' %}" type="text/css" />
  {% block head %}{% endblock %}
</head>

<body>
  <div class="header-top w-100 position-relative"></div>
  <header class="aui-main-header aui-pri-header">
    <a href='{% url "accounts:home" %}' class="aui-skip-content">Skip to main
      content</a>
    <nav
      class="py-2 m-0 w-100 position-relative navbar-expand-lg justify-content-between aui-header-content aui-pri-header-t">
      <div
        class="position-absolute logo-container text-center d-flex align-items-center flex-column justify-content-center">
        <a href='{% url "accounts:home" %}'>
          <div class="logo">
            <span class="campus">CAMPUS</span>
            <span class="cart">CART</span>
          </div>
        </a>
      </div>
      <button class="navbar-toggler ml-2 px-0 hamburger" type="button" data-toggle="collapse" data-target="#toggleNav"
        aria-controls="toggleNav" aria-expanded="false"><i class="aha-icon-hamburger"></i></button>
      <div class="justify-content-lg-center collapse navbar-collapse aui-pri-nav" id="toggleNav">
        <ul class="navbar-nav mx-lg-3 flex-lg-row flex-column">
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "accounts:home" %}' class="btn btn-text nav-link">Home</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "products:home" %}' class="btn btn-text nav-link">Products</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "books:home" %}' class="btn btn-text nav-link">Books</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "events:event-home" %}' class="btn btn-text nav-link">Events</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "freestuff:home" %}' class="btn btn-text nav-link">It's Free</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "lostfound:home" %}' class="btn btn-text nav-link">Lost & Found</a>
          </li>
          <li class="d-flex nav-item px-lg-3">
            <a href='{% url "rentals:home" %}' class="btn btn-text nav-link">Rentals</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="profile-pic-container position-absolute dropdown dropleft ">
      <img src="{{ request.user.profile.profile_image.url }}" class="profile-pic dropdown-toggle" id="navDropdown1"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" alt="Profile Pic" />
      <div class="dropdown-menu profile-dropdown" aria-labelledby="navDropdown1" role="menu">
        <ul class="p-0 m-0">
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:profile" %}'><span
                class="material-symbols-outlined">
                person
              </span>Update Profile</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:user-listing" %}'><span
                class="material-symbols-outlined">
                inventory
              </span>My Listings</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:item-request" %}'><span
                class="material-symbols-outlined">
                search
              </span>Request an Item</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:login-history" %}'>
              <span class="material-symbols-outlined">
                history
              </span>My Login History</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:change-password" %}'>
              <span class="material-symbols-outlined">
                history
              </span>Change Password</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:change-theme" %}'>
              <span class="material-symbols-outlined">
                palette
              </span>Change Theme</a></li>
          <li><a class="dropdown-item py-2 d-flex align-items-center" href='{% url "accounts:logout" %}'>
              <span class="material-symbols-outlined">
                logout
              </span>Sign Out</a></li>
        </ul>
      </div>
    </div>
    <div class="notification-icon position-absolute">
      <a href="{% url 'accounts:notifications' %}"
        class="icon-button position-relative d-flex align-items-center justify-content-center" id="notificationdrop">
        <span class="material-symbols-outlined notification-svg">
          notifications
        </span>
        <span class="icon-button__badge">{% live_notify_badge %}</span>
      </a>
    </div>
  </header>
  {% if messages%}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} rounded-0 mb-0 justify-content-center align-items-center">
    {{ message }}
    <button type="button" class="ml-4 close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif%}
  <div class="content p-1 mt-5 mb-5">

    {% block content %}
    {% endblock %}
  </div>
  <div class="wrapper display-none">
    <div class="spinner"></div>
  </div>
  <footer>©️ 2024 <a href="/">Campus Cart</a> | <a href="{% url 'accounts:contactus' %}">Contact Us</a></footer>
</body>
<script>
  const profileURL = document.querySelectorAll('.profile-link-url');
  if (profileURL.length > 0) {
    profileURL.forEach((url) => {
      url.addEventListener('click', () => {
        const wrapper = document.querySelector('.wrapper');
        wrapper.classList.remove('display-none');
      })
    })
  }
</script>

</html>

templates/notifications.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{{ block.super }}
{% if theme == 'primary' %}
<link rel="stylesheet" href="{% static 'css/notifications.css' %}" type="text/css" />
{% else %}
<link rel="stylesheet" href="{% static 'css/notifications-custom.css' %}" type="text/css" />
{% endif %}
{% endblock %}
{% block content %}
<div class="container position-relative">
  <div class="pt-4">
    <h1>Your {{title}}</h1>
    <div class="notification-header-underline"></div>
  </div>
  <div class="mt-4">
    <div class="notification-container d-flex flex-column w-75 m-auto">
      <div class="filter-buttons">Filters:
        <a href="?filter-by=upload" class="btn ml-2 btn btn btn-outline-warning btn-sm filter-button">Upload</a>
        <a href="?filter-by=request" class="btn  btn btn-outline-warning btn-sm filter-button">Request</a>
        <a href="?filter-by=comment" class="btn  btn btn-outline-warning btn-sm filter-button">Comment</a>
        <a href="?filter-by=all" class="btn  btn btn-outline-warning btn-sm filter-button">All</a>
      </div>
      {% if notifications %}
      {% for notification in notifications %}
      <div class="notification-box d-flex align-items-center">
        <a href="{% url 'accounts:profile-view' notification.actor.username %}"
          class="notification-user-pic-container"><img src="{{ notification.actor.profile.profile_image.url }}"
            class="profile-pic" alt="Profile Pic" />
        </a>
        <div class="notification-description">
          <div>
            {%if notification.verb == 'Upload' %}
            <b>{{ notification.actor.first_name }} {{ notification.actor.last_name }}</b> uploaded a new
            Item
            {% elif notification.verb == 'Comment' %}
            <b>{{ notification.actor.first_name }} {{ notification.actor.last_name }}</b> commented on your
            profile
            {% endif %}
          </div>
          <p>
            {% autoescape off %}
            {{ notification.description }} <a
              href="MSTeams:/l/chat/0/0?users={{notification.actor.email}}&message=Is it available"
              style="color: rgb(18, 56, 128);text-decoration: none;">Message User</a>
            {% endautoescape %}
          </p>
          <div>{{ notification.timestamp }}</div>
          <br />
        </div>
      </div>
      {% endfor %}
      {% else %}
      <h2 class="text-center mt-4">No New Notifications to display.</h2>
      {% endif %}
    </div>
  </div>
</div>
<script>
  const profilePic = document.querySelectorAll('.notification-user-pic-container');
  if (profilePic.length > 0) {
    profilePic.forEach((url) => {
      url.addEventListener('click', () => {
        const wrapper = document.querySelector('.wrapper');
        wrapper.classList.remove('display-none');
      })
    })
  }
</script>
{% endblock content %}